{{- if .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.serviceName }}-k6-analysis
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: k6-test
      count: 1
      initialDelay: {{ .Values.rollout.analysis.initialDelay | default "30s" }}
      provider:
        job:
          spec:
            template:
              metadata:
                labels:
                  k6-test: {{ .Values.serviceName | quote }}
              spec:
                imagePullSecrets:
                  - name: {{ .Values.serviceName }}-ghcr-docker-config
                containers:
                  - name: k6
                    image: {{ .Values.container.image.repository }}-tester:{{ .Values.container.image.tag }}
                    args:
                      - run
                      - --quiet
                      - /tests/smoke.js
                    env:
                      - name: TARGET_URL
                        value: "http://{{ .Values.serviceName }}.{{ .Values.namespace }}.svc.cluster.local"
                restartPolicy: Never
            backoffLimit: 0
            ttlSecondsAfterFinished: 300
      successCondition: result.contains("PASS")
      failureCondition: result.contains("FAIL")

    - name: success-rate
      initialDelay: {{ .Values.rollout.analysis.initialDelay | default "30s" }}
      interval: 30s
      count: {{ .Values.rollout.analysis.duration | default 5 }}
      successCondition: result[0] >= {{ .Values.rollout.analysis.successRate | default 0.95 }}
      failureCondition: result[0] < {{ .Values.rollout.analysis.successRate | default 0.95 }}
      provider:
        prometheus:
          address: "{{ .Values.rollout.analysis.prometheusAddress | default "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090" }}"
          query: >-
            sum(rate(istio_requests_total{destination_service_name="{{ .Values.serviceName }}",destination_service_namespace="{{ .Release.Namespace }}",response_code!~"5.*"}[2m])) /
            sum(rate(istio_requests_total{destination_service_name="{{ .Values.serviceName }}",destination_service_namespace="{{ .Release.Namespace }}"}[2m]))

    # P95 latency threshold
    - name: p95-latency
      initialDelay: {{ .Values.rollout.analysis.initialDelay | default "30s" }}
      interval: 30s
      count: {{ .Values.rollout.analysis.duration | default 5 }}
      successCondition: result[0] <= {{ .Values.rollout.analysis.maxP95Latency | default 500 }}
      failureCondition: result[0] > {{ .Values.rollout.analysis.maxP95Latency | default 500 }}
      provider:
        prometheus:
          address: "{{ .Values.rollout.analysis.prometheusAddress | default "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090"}}"
          query: >-
            histogram_quantile(0.95,sum(rate(istio_request_duration_milliseconds_bucket{destination_service_name="{{ .Values.serviceName }}",destination_service_namespace="{{ .Release.Namespace }}"}[2m])) by (le))

    # Error rate threshold
    - name: error-rate
      initialDelay: {{ .Values.rollout.analysis.initialDelay | default "30s" }}
      interval: 30s
      count: {{ .Values.rollout.analysis.duration | default 5 }}
      successCondition: result[0] <= {{ .Values.rollout.analysis.maxErrorRate | default 0.01 }}
      failureCondition: result[0] > {{ .Values.rollout.analysis.maxErrorRate | default 0.01 }}
      provider:
        prometheus:
          address: "{{ .Values.rollout.analysis.prometheusAddress | default "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090" }}"
          query: >-
            sum(rate(istio_requests_total{destination_service_name="{{ .Values.serviceName }}",destination_service_namespace="{{ .Release.Namespace }}",response_code=~"5.*"}[2m])) /
            sum(rate(istio_requests_total{destination_service_name="{{ .Values.serviceName }}",destination_service_namespace="{{ .Release.Namespace }}"}[2m]))

{{- end }}