apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-ghcr-docker-config
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.container.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.serviceName }}-ghcr-docker-config
    creationPolicy: Owner
    template:
      type: 'kubernetes.io/dockerconfigjson'
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: shared/ghcr/dockerconfigjson
        property: dockerconfigjson
  refreshInterval: 1m

