{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.serviceName }}-http-route
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ .Values.ingress.host | quote }}
  parentRefs:
    - name: {{ .Values.serviceName }}-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.service.port | default 80 }}
{{- end }}
