{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.serviceName }}-tls-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.serviceName }}-tls-cert
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
