{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.dbname }}-db-cluster
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.instances | default 1 }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.dbname }}
      owner: {{ .Values.postgres.owner }}
      secret:
        name: {{ .Values.postgres.dbname }}-db-secret
  serviceAccountTemplate:
    metadata:
      name: {{ .Values.postgres.dbname }}-sa
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: {{ .Values.postgres.pgVersionMajor }}
  storage:
    storageClass: {{ .Values.postgres.storageClass }}
    size: {{ .Values.postgres.storageSize }}
  resources:
  {{ .Values.postgres.resources | toYaml | nindent 2 }}
{{- end }}
