workloadType: BASIC_CONTAINER_ROLLOUT
serviceName: &svcName basic-service
nameOverride: *svcName
serviceCatalog: unset
basicMonitoring:
  enabled: true
namespace: default
environment: unset
serviceAccount: ""
revisionHistoryLimit: 2
ingress:
  enabled: false
  host: ""
service:
  port: 80
key: "abc"
container:
  vault:
    key: "path_to_secret"
    server: "http://vault.vault.svc.cluster.local:8200"
    role: "external-secrets-role"
  secretStore:
    name: vault-backend
  replicas: 0
  image:
    repository: unset
    tag: latest
    digest: unset
  containerPorts:
    - portName: "http"
      portNumber: 8080
      protocol: "TCP"
      servicePort: 80
  resources:
    requests:
      cpu: "0.2"
      memory: "100Mi"
    limits:
      cpu: "0.5"
      memory: "256Mi"
  secretRefreshInterval: 5m
  livenessProbe:
    enabled: true
    type: "http"
    path: "/v1/health"
    port: 8080
    scheme: "HTTP"
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    type: "http"
    path: "/v1/health"
    port: 8080
    scheme: "HTTP"
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  hpa:
    enabled: false
    targetCpu: 80
    minReplicas: 1
    maxReplicas: 3
  environment: []
  secrets: []
postgres:
  enabled: false
  instances: 1
  dbname: "postgres"
  #the owner name must match the username in the external secret
  owner: "postgres"
  pgVersionMajor: 16
  storageSize: "250Mi"
  storageClass: "nfs-db-storage"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
rollout:
  analysisTemplate:
    enabled: true
    initialDelay: 30s
    duration: "5"
    successRate: 0.95
    maxP95Latency: 500
    maxErrorRate: 0.01
  analysis:
    successfulRunHistoryLimit: 2
    unsuccessfulRunHistoryLimit: 2
  strategy:
    canary:
      maxUnavailable: 0
      maxSurge: 1
      steps:
      - pause: { duration: 5s }